### ISSUE TITLE
Конвертировать цены в рубли

### ISSUE THREAD

**Issue by ivantsyganov** [retailcrm/moysklad-catalog#31]
Доброго дня. У меня цены в каталоге в евро. Как при выгрузке каталога сделать, чтобы цена продажи и закупочная цена сохранялись в рублях, конвертированные по текущему курсу в Мой Склад?

**Comment by gwinn** [comment]
В данном случае Вам необходимо модифицировать скрипт, текущее значение курса из МС можно получить с помощью https://online.moysklad.ru/api/remap/1.1/entity/currency/{uuid_валюты}, полученное значение можно будет использовать для можификации значения в следующих строках:

* https://github.com/retailcrm/moysklad-catalog/blob/master/MoySkladICMLParser.php#L333-L339
* https://github.com/retailcrm/moysklad-catalog/blob/master/MoySkladICMLParser.php#L357-L363
