### ISSUE TITLE
Единицы измерения

### ISSUE THREAD

**Issue by derqas** [retailcrm/moysklad-catalog#34]
if (isset($assortiment['uom']) && isset($assortiment['uom']['code'])) {
                        $products[$assortiment['id']]['unit'] = array (
                            'code' => $assortiment['uom']['code'],
                            'name' => $assortiment['uom']['name'],
                            'description' => $assortiment['uom']['description'],
                        );
                    } elseif (isset($assortiment['product']['uom']) && isset($assortiment['product']['uom']['code'])) {
                        $products[$assortiment['id']]['unit'] = array (
                            'code' => $assortiment['product']['uom']['code'],
                            'name' => $assortiment['product']['uom']['name'],
                            'description' => $assortiment['product']['uom']['description'],
                        );
                    }...
нужно дополнить
elseif (isset($assortiment['product']['uom']) && isset($assortiment['product']['uom']['externalCode'])) {
                        $products[$assortiment['id']]['unit'] = array (
                            'code' => $assortiment['product']['uom']['externalCode'],
                            'name' => str_replace(' ','',$assortiment['product']['uom']['name']),
                            'description' => $assortiment['product']['uom']['name'],
                        );
                    } elseif (isset($assortiment['uom']) && isset($assortiment['uom']['externalCode'])) {
                        $products[$assortiment['id']]['unit'] = array (
                            'code' => $assortiment['uom']['externalCode'],
                            'name' => str_replace(' ','',$assortiment['product']['uom']['name']),
                            'description' => $assortiment['product']['uom']['name'],
                        );
                    }
...
у пользовательских единиц измерения нет поля code

**Comment by sergeygw1990** [comment]
Благодарим вас за ваше замечание. Правки будут внесены

**Comment by derqas** [comment]
Ok.
