### ISSUE TITLE
Как из МоегоСклада передать второй тип цен товаров (помимо базового) в retaiCRM?

### ISSUE THREAD

**Issue by GreenRobot777** [retailcrm/moysklad-catalog#39]
Как я понимаю, формат ICML не позволяет загружать несколько типов цен из XML-файла.
Есть ли такая возможность в данном модуле и в какую сторону копать?

Пример:
Розничная цена - базовая
Оптовая цена - пользовательская

**Comment by sergeygw1990** [comment]
В скрипте генерации каталога данный функционал не заложен по причине того, что типы цен нельзя передавать в каталоге. Типы цен настраиваются непосредственно в CRM.
