### ISSUE TITLE
Не генерируется файл на выходе

### ISSUE THREAD

**Issue by pavloz** [retailcrm/moysklad-catalog#40]
Добрый день! Сделал все по инструкции, но вот незадача - не генерируется файл на выходе( В чем может быть проблема?

**Comment by GreenRobot777** [comment]
@pavloz, покажите лог веб-сервера, пожалуйста. Там наверняка ответ.

**Comment by sergeygw1990** [comment]
Без лога ошибок причины описать затруднительно. Это может быть и некорректные доступы и иные ошибки исполнения кода. Так же катало не будет сгенерирован если не были получены товары или категории товаров
