### ISSUE TITLE
Добавление изображений

### ISSUE THREAD

**Issue by sergey3145** [retailcrm/moysklad-catalog#41]
Добрый день! Не могу загрузить изображения товара. У меня хостинг на Nic.ru получился вот такой файл example.php
include __DIR__ . '/MoySkladICMLParser.php';

// configure
$parser = new MoySkladICMLParser(
    'admin@mymail',
    'password',
    'mysite',
$options = array('imageDownload' =>
array(
        'site' => 'https://mysite.ru',
        'pathToImage' => 'docs/icml/img')
    ),
    array(
        'directory' => __DIR__,
        'file' => 'catalog.xml',
    )
);

// generate
$parser->generateICML();

**Comment by sergeygw1990** [comment]
Не совсем корректно заполнен файл настроек и запуска. Вот корректный пример на основе вашего кода 
include DIR . '/MoySkladICMLParser.php';

// configure
$parser = new MoySkladICMLParser(
'admin@mymail',
'password',
'mysite',
array(
	'directory' => DIR,
	'file' => 'catalog.xml',
	'imageDownload' =>
	array(
		'site' => 'https://mysite.ru',
		'pathToImage' => 'docs/icml/img')
	),
);

// generate
$parser->generateICML();

**Comment by sergey3145** [comment]
Скорректировл так но, изображения в папке не появились, а еще имя файла каталога стало вместо mysite.catalog.xml просто catalog.xml
С запятой в средней строке следущего кода ошибка
 'pathToImage' => 'docs/icml/img')
),
);
Parse error: syntax error, unexpected ')' in /home/................................php on line 20

**Comment by sergeygw1990** [comment]
`include DIR . '/MoySkladICMLParser.php';

// configure
$parser = new MoySkladICMLParser(
'admin@mymail',
'password',
'mysite',
array(
	'directory' => DIR,
	'file' => 'catalog.xml',
	'imageDownload' =>
	array(
		'site' => 'https://mysite.ru',
		'pathToImage' => 'docs/icml/img'),
	)
);
// generate
$parser->generateICML();`
Прошу прощения. Допустил опечатку с запятой.
