### ISSUE TITLE
Проблема с генерацией xml

### ISSUE THREAD

**Issue by vasdidas** [retailcrm/moysklad-catalog#42]
Подскажите пожалуйста где в скрипте нужно добавить код для объявления " Content-Type"?

Проблема появилась при добавлении сгенерированного файла xml в систему retailCRM

Лог ошибки в retailCRM:
2018-08-24 16:30:30: Load started
2018-08-24 16:30:54: HTTP-заголовок "Content-Type" должен содержать одно из следующих значений [application/xml, text/xml].
Получено значение "text/html".
2018-08-24 16:30:54: Loading end

**Comment by iyzoer** [comment]
Заголовок в данном случае устанавливается веб сервером. Проверьте конфигурацию веб сервера или обратитесь в техподдержку хостинга.

**Comment by sergeygw1990** [comment]
Вам нужно обратится к хостингу с указанной ошибкой. Так же рекомендую указать ссылку по которой вы пытаетесь получить файл каталога.

**Comment by vasdidas** [comment]
Благодарю за ответ! 
Проблема решена

**Comment by aleksandrvozniukconnect** [comment]
@vasdidas подскажите пожалуйста, как удалось решить проблему?
