### ISSUE TITLE
Есть ли возможность добавить в скрипт генерацию остатков товара ?

### ISSUE THREAD

**Issue by vasdidas** [retailcrm/moysklad-catalog#43]
Подскажите пожалуйста есть ли возможность улучшить данный скрипт 
добавив функцию парсинга остатков товара из "мой склад" в генерируемый файл - чтобы на выходе получился xml файл с текущими остатками по сгенерированным товарам?

**Comment by sergeygw1990** [comment]
В данном случае требуется доработка модуля непосредственно вами. Получить остаток можно из переменной $assortiment по ключу "quantity". Добавьте присвоение в массив $products[$assortiment['id']] . А в методе ICMLCreate
