### ISSUE TITLE
Опять проблема с изображениями

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/moysklad-catalog#44]
Сам файл 

date_default_timezone_set('Europe/Moscow');
include __DIR__ . '/MoySkladICMLParser.php';

// configure
$parser = new MoySkladICMLParser(
    'admin@mylogin,
    'password',
    'mystore',
array(
'directory' => __DIR__,
'file' => 'mycatalog.xml',
'imageDownload' =>
array(
'site' => 'http://mysite.net',
'pathToImage' => 'goods'),
)
);
// generate
$parser->generateICML();
echo 'It is done';

1. не загружаются изображения в каталог из файла
2. когда пытаюсь поменять путь к папке с изображениями на 'pathToImage' => 'moysklad/goods'), то ожидаю, что ссылка будет выглядеть примерно так - http://mysite.net/moysklad/goods/image.jpg
но выдается ссылка вида http://mysite.net/goods/image.jpg Почему так?``

**Comment by sergeygw1990** [comment]
`pathToImage` - в данном ключе нужно указывать путь до директории с изображениями от корня сайта (Корень сайта так же нужно указать)
