### ISSUE TITLE
Зависание скрипта

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/moysklad-catalog#45]
Переехал на новый хостинг. Памяти под php 256мб, время исполнения скрипта 300 сёк.
Скрипт постоянно убивает я в связи с превышение времени исполнения. По ssh при ручном запуске тоже самое. На других хостингах все нормально, а Ukraine.com проблема. Хостинг пишет, что явных ошибок в консоли нет и нужно обратиться к разработчику, что продебажить скрипт. Я в дебаге php вообще новичок, но скрипт очень нужен.

**Comment by gwinn** [comment]
Время работы связано с объемами данных получаемыми по сети, оптимизировать особо не выйдет.

> На других хостингах все нормально, а Ukraine.com проблема.

Возможно стоит сменить хостинг.
