### ISSUE TITLE
Выборка из склада

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/moysklad-catalog#47]
Как нужно модифицировать модуль, чтобы получить icml файл с остатками только по конкретному складу в Мой склад, при наличии нескольких?

**Comment by sergeygw1990** [comment]
В данном случае потребуется серьезная модификация скрипта генерации с использованием json api сервиса Мой Склад.

**Comment by sergejfreelancer** [comment]
Сколько будет стоить такая модификация? Она очень нужна во времена дропшипинга и разделения оффлайн и онлайн складов

**Comment by gwinn** [comment]
Можете обратиться по поводу разработки тут - https://www.retailcrm.ru/partners
