### ISSUE TITLE
Не отображаются изображения в retailCRM

### ISSUE THREAD

**Issue by victormanyakov** [retailcrm/moysklad-catalog#49]
Изображения не отображаются, хотя в xml файле ссылки формируются правильно, при вводе их в адресную строку они отображаются.

**Comment by sergeygw1990** [comment]
При переходе по ссылке изображения не происходит редирект ?

**Comment by victormanyakov** [comment]
Нет, ссылка прямая вида mysite.ru/wp-content/uploads/img001.jpg

**Comment by sergejfreelancer** [comment]
Так, у вас ссылка битая. Попробуйте из свого коммента перейти. 404 ошибка

**Comment by victormanyakov** [comment]
Я просто поменял наш сайт на mysite.ru :)

**Comment by sergejfreelancer** [comment]
Так, покажите кусок yml каталога. Тут же не экстрасенсы. Или кусок блока файла run.php, где прописаны опции изображений
